'use client';

import { useState } from 'react';
import { Wand2, Loader, Download } from 'lucide-react';
import { motion } from 'framer-motion';

interface DesignOutput {
  layout: string;
  colors: Record<string, string>;
  fonts: Record<string, string>;
  sections: Array<{
    type: string;
    [key: string]: any;
  }>;
}

export default function DesignGenerator() {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [design, setDesign] = useState<DesignOutput | null>(null);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      setError('Please enter a design description');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/design/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) throw new Error('Failed to generate design');

      const data = await response.json();
      setDesign(data.design);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  const handleExport = () => {
    if (!design) return;

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Design</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: ${design.fonts.body};
      background: ${design.colors.background};
      color: ${design.colors.text};
    }
    .hero {
      background: linear-gradient(135deg, ${design.colors.primary}, ${design.colors.secondary});
      padding: 100px 40px;
      text-align: center;
      color: white;
    }
    .hero h1 { font-size: 48px; margin-bottom: 20px; }
    .cta-button {
      background: ${design.colors.primary};
      color: white;
      padding: 12px 32px;
      border: none;
      border-radius: 8px;
      cursor: pointer;
      font-size: 16px;
    }
  </style>
</head>
<body>
  <div class="hero">
    <h1>Your Product Title</h1>
    <p>Generated by Jarvis Design AI</p>
    <button class="cta-button">Get Started</button>
  </div>
</body>
</html>
    `;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'jarvis-design.html';
    a.click();
  };

  return (
    <div className="w-full max-w-4xl mx-auto p-6">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass rounded-2xl p-8"
      >
        <h2 className="text-3xl font-bold mb-4 gradient-text">Design Generator</h2>

        <div className="space-y-4">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Describe your design idea... (e.g., 'Premium SaaS landing page for AI tool with dark theme')"
            className="w-full h-24 p-4 rounded-xl bg-slate-900 border border-slate-700 text-white placeholder-slate-400 focus:outline-none focus:border-violet-500"
          />

          {error && (
            <div className="p-4 bg-red-500/10 border border-red-500/50 rounded-lg text-red-200 text-sm">
              {error}
            </div>
          )}

          <button
            onClick={handleGenerate}
            disabled={loading}
            className="w-full py-3 rounded-xl bg-gradient-to-r from-violet-500 to-cyan-400 text-slate-950 font-semibold flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {loading ? (
              <>
                <Loader size={20} className="animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Wand2 size={20} />
                Generate Design
              </>
            )}
          </button>
        </div>

        {design && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-8 p-6 bg-slate-900/50 rounded-xl border border-slate-700"
          >
            <h3 className="text-xl font-semibold mb-4">Generated Design Config</h3>

            <div className="grid grid-cols-2 gap-4 mb-6">
              <div>
                <p className="text-sm text-slate-400 mb-2">Colors</p>
                <div className="space-y-2">
                  {Object.entries(design.colors).map(([key, value]) => (
                    <div key={key} className="flex items-center gap-2">
                      <div
                        className="w-8 h-8 rounded border border-slate-600"
                        style={{ backgroundColor: value }}
                      />
                      <span className="text-sm text-slate-300">{key}: {value}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <p className="text-sm text-slate-400 mb-2">Fonts</p>
                <div className="space-y-2">
                  {Object.entries(design.fonts).map(([key, value]) => (
                    <div key={key} className="text-sm text-slate-300">
                      <span className="font-semibold">{key}:</span> {value}
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <button
              onClick={handleExport}
              className="w-full py-2 rounded-lg bg-emerald-500/20 border border-emerald-500/50 text-emerald-200 font-semibold flex items-center justify-center gap-2 hover:bg-emerald-500/30"
            >
              <Download size={18} />
              Export as HTML
            </button>
          </motion.div>
        )}
      </motion.div>
    </div>
  );
}
